### ISSUE TITLE
Is py3DEP resampled data or derived directly from point clouds?

### ISSUE THREAD

**Issue by philipbaileynar** [cheginit/py3dep#2]
I am curious how py3DEP rasters are calculated? Are the data re-sampling precalculaed rasters or is it rasterizing a point cloud on-the-fly based on the spatial resolution requested by the user. In other words, if I request data at 1.456m cell resolution is this request being performed using a bilinear or nearest neighbour resample of an existing raster, or is a point cloud being rasterized at the requested resolution?

Here's some example code:

https://github.com/Riverscapes/riverscapes-tools/blob/3dep/packages/rscontext/research/3dep_testing.ipynb

**Comment by cheginit** [comment]
@philipbaileynar You can find the service specifications [here](https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer). The default method is bilinear. In general, 3DEP uses all the available data on the server with different resolutions for resampling the data within the requested region on the server-side. You can find the availability map of elevation data sources that 3DEP uses [here](https://prd-tnm.s3.amazonaws.com/LidarExplorer/index.html).
If it's useful I can add a flag to select the resampling method, this RESTful service can perform resampling using these methods: `RSP_BilinearInterpolation` | `RSP_CubicConvolution` | `RSP_Majority` | `RSP_NearestNeighbor`

**Comment by philipbaileynar** [comment]
@cheginit this service is excellent, but I still have a LOT of questions. Might you be available for a quick video chat to discuss py3DEP service please?

**Comment by cheginit** [comment]
Sure, we can.

**Comment by philipbaileynar** [comment]
Thanks! can you send an email to info@northarrowresearch.com with a couple of days and times over the next week that work for you. I will reply with a meeting invite. Be sure to specify your timezone. We are in Pacific time.

**Comment by cheginit** [comment]
Sure, I just did.

**Comment by cheginit** [comment]
I am going to close this for now, please feel free to reopen if you have any other questions.
